//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopPedido.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbOnlineStoreModel : DbContext
    {
        public dbOnlineStoreModel()
            : base("name=dbOnlineStoreModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCategories> tblCategories { get; set; }
        public DbSet<tblInvoice> tblInvoice { get; set; }
        public DbSet<tblOrder> tblOrder { get; set; }
        public DbSet<tblProducts> tblProducts { get; set; }
        public DbSet<tblUser> tblUser { get; set; }
        public DbSet<user_invoices> user_invoices { get; set; }
        public DbSet<vw_getallproducts> vw_getallproducts { get; set; }
        public DbSet<vw_productosPedido> vw_productosPedido { get; set; }
        public DbSet<getallorders> getallorders { get; set; }
        public DbSet<getallorderusers> getallorderusers { get; set; }
        public DbSet<tblEstados> tblEstados { get; set; }
        public DbSet<tblTracking> tblTracking { get; set; }
        public DbSet<vw_TrackingEstados> vw_TrackingEstados { get; set; }
        public DbSet<vw_TrackingUsuarios> vw_TrackingUsuarios { get; set; }
        public DbSet<vw_comboPedidos> vw_comboPedidos { get; set; }
        public DbSet<tblProveedor> tblProveedor { get; set; }
        public DbSet<tblMascota> tblMascota { get; set; }
        public DbSet<tblRaza> tblRaza { get; set; }
        public DbSet<tblServicio> tblServicio { get; set; }
        public DbSet<vw_listaMascotas> vw_listaMascotas { get; set; }
        public DbSet<tblTipo> tblTipo { get; set; }
        public DbSet<tblTipoPago> tblTipoPago { get; set; }
        public DbSet<tblFactura> tblFactura { get; set; }
        public DbSet<tblTransaccion> tblTransaccion { get; set; }
        public DbSet<tblFacturaDetalles> tblFacturaDetalles { get; set; }
        public DbSet<vw_ListaFacturas> vw_ListaFacturas { get; set; }
        public DbSet<vw_FacturasDetalles> vw_FacturasDetalles { get; set; }
    }
}
