//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopPedido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategories
    {
        public tblCategories()
        {
            this.tblProducts = new HashSet<tblProducts>();
        }
    
        public int CatId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<tblProducts> tblProducts { get; set; }
    }
}
