//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopPedido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFactura
    {
        public tblFactura()
        {
            this.tblFacturaDetalles = new HashSet<tblFacturaDetalles>();
        }
    
        public int idFactura { get; set; }
        public string numero { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idTipoPago { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<decimal> FinalTotal { get; set; }
    
        public virtual ICollection<tblFacturaDetalles> tblFacturaDetalles { get; set; }
    }
}
