//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopPedido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public tblOrder()
        {
            this.tblInvoice = new HashSet<tblInvoice>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> ProID { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PayMethod { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        public virtual ICollection<tblInvoice> tblInvoice { get; set; }
        public virtual tblProducts tblProducts { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
