//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopPedido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProveedor
    {
        public int idProv { get; set; }
        public string nomProv { get; set; }
        public string RUC { get; set; }
        public int estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
