//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopPedido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducts
    {
        public tblProducts()
        {
            this.tblOrder = new HashSet<tblOrder>();
        }
    
        public int ProID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Unit { get; set; }
        public string Image { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Serie { get; set; }
        public string Marca { get; set; }
        public string DescriptionHTML { get; set; }
        public string Image02 { get; set; }
        public string Image03 { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> idProv { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual tblCategories tblCategories { get; set; }
        public virtual ICollection<tblOrder> tblOrder { get; set; }
    }
}
