//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopPedido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServicio
    {
        public int idServ { get; set; }
        public string nomServ { get; set; }
        public Nullable<decimal> precServ { get; set; }
        public string desServ { get; set; }
        public string horarioServ { get; set; }
        public string fecServ { get; set; }
        public Nullable<int> enabled { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public int idUser { get; set; }
    }
}
