//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopPedido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblInvoice = new HashSet<tblInvoice>();
            this.tblOrder = new HashSet<tblOrder>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleType { get; set; }
        public string apellidos { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fecharegistro { get; set; }
        public Nullable<int> id_veterinario { get; set; }
    
        public virtual ICollection<tblInvoice> tblInvoice { get; set; }
        public virtual ICollection<tblOrder> tblOrder { get; set; }
    }
}
