//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopPedido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_listaMascotas
    {
        public int idMasc { get; set; }
        public string nomMasc { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> estado { get; set; }
        public string nomRaza { get; set; }
        public string cliente { get; set; }
    }
}
