//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopPedido.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TrackingEstados
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
    }
}
